# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-24 18:43
from __future__ import unicode_literals

from django.db import migrations, models


def forward(apps, schema_editor):
    Note = apps.get_model("enibar", "Note")
    HistoryLine = apps.get_model("enibar", "HistoryLine")

    for note in Note.objects.all():
        print(note.nickname, note.foreign_id)
        HistoryLine.objects.filter(note=note.nickname).update(note_id=note.foreign_id)

def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('enibar', '0007_auto_20160113_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyline',
            name='note_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(forward, backward)
    ]
