# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='homepage_highlight',
            field=models.BooleanField( default = False ),
        ),
    ]
