# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asso', '0003_auto_20160219_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='asso',
            name='homepage_highlight',
            field=models.BooleanField( default = False ),
        ),
        migrations.AddField(
            model_name='asso',
            name='priority',
            field=models.IntegerField( default = 0 ),
        ),
    ]
